version: '3'

services:
  database:
    image: mariadb:10.7.3-focal
    restart: always
    ports:
      - 3316:3306
    volumes:
      - database_volume:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_PASSWORD: "0000"
      MYSQL_DATABASE: "db_cms"
      MYSQL_USER: "cmsuser"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 15

  app:
    container_name: rems-for-organisations-app
    image: "ghcr.io/bearlike/rems-for-organisations:latest"
    restart: on-failure
    depends_on:
      - database
    ports:
      - 8989:5000
    volumes:
      - generated_certificates_volume:"/app/public/Generated Certificate"
    environment:
      MYSQL_HOST: database
      MYSQL_PASSWORD: "0000"
      MYSQL_USER: "cmsuser"

volumes:
  database_volume:
  generated_certificates_volume:
